export default {
  INIT_BTN_INDEX: 0,
  RECENT_INDEX: 0,
  DATA_INDEX: 1,
  EVENT_INDEX: 2,
  NEWS_INDEX: 3,
  ME_INDEX: 4,
  DOUBLE_CLICK_INTERVAL: 400,
  RECENT_LIMIT_ITEM_CNT: 100,

  WEI_PER_ETH: 1e18,
};
